// © 2025 Platform Engineering Labs Inc.
//
// SPDX-License-Identifier: FSL-1.1-ALv2

package resources

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cdn/armcdn/v2"
	"github.com/platform-engineering-labs/formae-plugin-azure/pkg/client"
	"github.com/platform-engineering-labs/formae-plugin-azure/pkg/config"
	"github.com/platform-engineering-labs/formae-plugin-azure/pkg/prov"
	"github.com/platform-engineering-labs/formae-plugin-azure/pkg/registry"
	"github.com/platform-engineering-labs/formae/pkg/plugin/resource"
)

const ResourceTypeCdnAFDEndpoint = "AZURE::Cdn::AFDEndpoint"

// cdnAFDEndpointsAPI is the narrow slice of *armcdn.AFDEndpointsClient used by
// the provisioner. Create/Delete are LRO; Get is synchronous. Update is handled
// through BeginCreate (PUT create-or-update) so the request body stays a full
// armcdn.AFDEndpoint for both operations.
type cdnAFDEndpointsAPI interface {
	BeginCreate(ctx context.Context, resourceGroupName string, profileName string, endpointName string, endpoint armcdn.AFDEndpoint, options *armcdn.AFDEndpointsClientBeginCreateOptions) (*runtime.Poller[armcdn.AFDEndpointsClientCreateResponse], error)
	Get(ctx context.Context, resourceGroupName string, profileName string, endpointName string, options *armcdn.AFDEndpointsClientGetOptions) (armcdn.AFDEndpointsClientGetResponse, error)
	BeginDelete(ctx context.Context, resourceGroupName string, profileName string, endpointName string, options *armcdn.AFDEndpointsClientBeginDeleteOptions) (*runtime.Poller[armcdn.AFDEndpointsClientDeleteResponse], error)
	NewListByProfilePager(resourceGroupName string, profileName string, options *armcdn.AFDEndpointsClientListByProfileOptions) *runtime.Pager[armcdn.AFDEndpointsClientListByProfileResponse]
}

func init() {
	registry.Register(ResourceTypeCdnAFDEndpoint, func(c *client.Client, cfg *config.Config) prov.Provisioner {
		return &CdnAFDEndpoint{
			api:      c.CdnAFDEndpointsClient,
			pipeline: c.Pipeline(),
			config:   cfg,
		}
	})
}

// CdnAFDEndpoint is the provisioner for an Azure Front Door endpoint
// (Microsoft.Cdn/profiles/afdEndpoints).
type CdnAFDEndpoint struct {
	api      cdnAFDEndpointsAPI
	pipeline runtime.Pipeline
	config   *config.Config
}

func cdnAFDEndpointIDParts(resourceID string) (rgName, profileName, endpointName string, err error) {
	rgName, names, err := armIDParts(resourceID, "profiles", "afdEndpoints")
	if err != nil {
		return "", "", "", err
	}
	return rgName, names["profiles"], names["afdEndpoints"], nil
}

func buildCdnAFDEndpointParams(props map[string]any, location string) armcdn.AFDEndpoint {
	params := armcdn.AFDEndpoint{
		Location:   stringPtr(location),
		Properties: &armcdn.AFDEndpointProperties{},
	}
	if v, ok := props["enabledState"].(string); ok && v != "" {
		params.Properties.EnabledState = to.Ptr(armcdn.EnabledState(v))
	}
	if v, ok := props["autoGeneratedDomainNameLabelScope"].(string); ok && v != "" {
		params.Properties.AutoGeneratedDomainNameLabelScope = to.Ptr(armcdn.AutoGeneratedDomainNameLabelScope(v))
	}
	return params
}

func serializeCdnAFDEndpointProperties(result armcdn.AFDEndpoint, rgName, profileName, endpointName string) (json.RawMessage, error) {
	props := make(map[string]any)
	props["resourceGroupName"] = rgName
	props["profileName"] = profileName
	if result.Name != nil {
		props["name"] = *result.Name
	} else {
		props["name"] = endpointName
	}
	if result.Location != nil {
		props["location"] = *result.Location
	}
	if result.ID != nil {
		props["id"] = *result.ID
	}
	if p := result.Properties; p != nil {
		if p.EnabledState != nil {
			props["enabledState"] = string(*p.EnabledState)
		}
		if p.AutoGeneratedDomainNameLabelScope != nil {
			props["autoGeneratedDomainNameLabelScope"] = string(*p.AutoGeneratedDomainNameLabelScope)
		}
		if p.HostName != nil {
			props["hostName"] = *p.HostName
		}
	}
	if tags := azureTagsToFormaeTags(result.Tags); tags != nil {
		props["Tags"] = tags
	}
	return json.Marshal(props)
}

func (e *CdnAFDEndpoint) Create(ctx context.Context, request *resource.CreateRequest) (*resource.CreateResult, error) {
	var props map[string]any
	if err := json.Unmarshal(request.Properties, &props); err != nil {
		return nil, fmt.Errorf("failed to parse resource properties: %w", err)
	}
	rgName, ok := props["resourceGroupName"].(string)
	if !ok || rgName == "" {
		return nil, fmt.Errorf("resourceGroupName is required")
	}
	profileName, ok := props["profileName"].(string)
	if !ok || profileName == "" {
		return nil, fmt.Errorf("profileName is required")
	}
	location, ok := props["location"].(string)
	if !ok || location == "" {
		return nil, fmt.Errorf("location is required")
	}
	endpointName, ok := props["name"].(string)
	if !ok || endpointName == "" {
		endpointName = request.Label
	}

	params := buildCdnAFDEndpointParams(props, location)
	if azureTags := formaeTagsToAzureTags(request.Properties); azureTags != nil {
		params.Tags = azureTags
	}

	poller, err := e.api.BeginCreate(ctx, rgName, profileName, endpointName, params, nil)
	if err != nil {
		return &resource.CreateResult{ProgressResult: &resource.ProgressResult{
			Operation:       resource.OperationCreate,
			OperationStatus: resource.OperationStatusFailure,
			ErrorCode:       operationErrorCode(err),
		}}, nil
	}

	expectedNativeID := fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Cdn/profiles/%s/afdEndpoints/%s",
		e.config.SubscriptionId, rgName, profileName, endpointName)

	if poller.Done() {
		result, err := poller.Result(ctx)
		if err != nil {
			return &resource.CreateResult{ProgressResult: &resource.ProgressResult{
				Operation:       resource.OperationCreate,
				OperationStatus: resource.OperationStatusFailure,
				ErrorCode:       operationErrorCode(err),
			}}, nil
		}
		propsJSON, err := serializeCdnAFDEndpointProperties(result.AFDEndpoint, rgName, profileName, endpointName)
		if err != nil {
			return nil, fmt.Errorf("failed to serialize AFDEndpoint properties: %w", err)
		}
		return &resource.CreateResult{ProgressResult: &resource.ProgressResult{
			Operation:          resource.OperationCreate,
			OperationStatus:    resource.OperationStatusSuccess,
			NativeID:           *result.ID,
			ResourceProperties: propsJSON,
		}}, nil
	}

	resumeToken, err := poller.ResumeToken()
	if err != nil {
		return nil, fmt.Errorf("failed to get resume token: %w", err)
	}
	reqIDJSON, err := encodeLROStart(lroOpCreate, resumeToken, expectedNativeID)
	if err != nil {
		return nil, err
	}
	return &resource.CreateResult{ProgressResult: &resource.ProgressResult{
		Operation:       resource.OperationCreate,
		OperationStatus: resource.OperationStatusInProgress,
		RequestID:       reqIDJSON,
		NativeID:        expectedNativeID,
	}}, nil
}

func (e *CdnAFDEndpoint) Read(ctx context.Context, request *resource.ReadRequest) (*resource.ReadResult, error) {
	rgName, profileName, endpointName, err := cdnAFDEndpointIDParts(request.NativeID)
	if err != nil {
		return nil, fmt.Errorf("invalid NativeID %s: %w", request.NativeID, err)
	}
	result, err := e.api.Get(ctx, rgName, profileName, endpointName, nil)
	if err != nil {
		return &resource.ReadResult{ErrorCode: operationErrorCode(err)}, nil
	}
	propsJSON, err := serializeCdnAFDEndpointProperties(result.AFDEndpoint, rgName, profileName, endpointName)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize AFDEndpoint properties: %w", err)
	}
	return &resource.ReadResult{ResourceType: ResourceTypeCdnAFDEndpoint, Properties: string(propsJSON)}, nil
}

func (e *CdnAFDEndpoint) Update(ctx context.Context, request *resource.UpdateRequest) (*resource.UpdateResult, error) {
	rgName, profileName, endpointName, err := cdnAFDEndpointIDParts(request.NativeID)
	if err != nil {
		return nil, fmt.Errorf("invalid NativeID %s: %w", request.NativeID, err)
	}
	var props map[string]any
	if err := json.Unmarshal(request.DesiredProperties, &props); err != nil {
		return nil, fmt.Errorf("failed to parse resource properties: %w", err)
	}
	location, ok := props["location"].(string)
	if !ok || location == "" {
		return nil, fmt.Errorf("location is required")
	}

	params := buildCdnAFDEndpointParams(props, location)
	if azureTags := formaeTagsToAzureTags(request.DesiredProperties); azureTags != nil {
		params.Tags = azureTags
	}

	poller, err := e.api.BeginCreate(ctx, rgName, profileName, endpointName, params, nil)
	if err != nil {
		return &resource.UpdateResult{ProgressResult: &resource.ProgressResult{
			Operation:       resource.OperationUpdate,
			OperationStatus: resource.OperationStatusFailure,
			NativeID:        request.NativeID,
			ErrorCode:       operationErrorCode(err),
		}}, nil
	}

	if poller.Done() {
		result, err := poller.Result(ctx)
		if err != nil {
			return &resource.UpdateResult{ProgressResult: &resource.ProgressResult{
				Operation:       resource.OperationUpdate,
				OperationStatus: resource.OperationStatusFailure,
				NativeID:        request.NativeID,
				ErrorCode:       operationErrorCode(err),
			}}, nil
		}
		propsJSON, err := serializeCdnAFDEndpointProperties(result.AFDEndpoint, rgName, profileName, endpointName)
		if err != nil {
			return nil, fmt.Errorf("failed to serialize AFDEndpoint properties: %w", err)
		}
		return &resource.UpdateResult{ProgressResult: &resource.ProgressResult{
			Operation:          resource.OperationUpdate,
			OperationStatus:    resource.OperationStatusSuccess,
			NativeID:           *result.ID,
			ResourceProperties: propsJSON,
		}}, nil
	}

	resumeToken, err := poller.ResumeToken()
	if err != nil {
		return nil, fmt.Errorf("failed to get resume token: %w", err)
	}
	reqIDJSON, err := encodeLROStart(lroOpUpdate, resumeToken, request.NativeID)
	if err != nil {
		return nil, err
	}
	return &resource.UpdateResult{ProgressResult: &resource.ProgressResult{
		Operation:       resource.OperationUpdate,
		OperationStatus: resource.OperationStatusInProgress,
		RequestID:       reqIDJSON,
		NativeID:        request.NativeID,
	}}, nil
}

func (e *CdnAFDEndpoint) Delete(ctx context.Context, request *resource.DeleteRequest) (*resource.DeleteResult, error) {
	rgName, profileName, endpointName, err := cdnAFDEndpointIDParts(request.NativeID)
	if err != nil {
		return nil, fmt.Errorf("invalid NativeID %s: %w", request.NativeID, err)
	}
	poller, err := e.api.BeginDelete(ctx, rgName, profileName, endpointName, nil)
	if err != nil {
		if operationErrorCode(err) == resource.OperationErrorCodeNotFound {
			return &resource.DeleteResult{ProgressResult: &resource.ProgressResult{
				Operation:       resource.OperationDelete,
				OperationStatus: resource.OperationStatusSuccess,
				NativeID:        request.NativeID,
			}}, nil
		}
		return &resource.DeleteResult{ProgressResult: &resource.ProgressResult{
			Operation:       resource.OperationDelete,
			OperationStatus: resource.OperationStatusFailure,
			NativeID:        request.NativeID,
			ErrorCode:       operationErrorCode(err),
		}}, fmt.Errorf("failed to start AFDEndpoint deletion: %w", err)
	}
	resumeToken, err := poller.ResumeToken()
	if err != nil {
		return nil, fmt.Errorf("failed to get resume token: %w", err)
	}
	reqIDJSON, err := encodeLROStart(lroOpDelete, resumeToken, request.NativeID)
	if err != nil {
		return nil, err
	}
	return &resource.DeleteResult{ProgressResult: &resource.ProgressResult{
		Operation:       resource.OperationDelete,
		OperationStatus: resource.OperationStatusInProgress,
		RequestID:       reqIDJSON,
		NativeID:        request.NativeID,
	}}, nil
}

func (e *CdnAFDEndpoint) Status(ctx context.Context, request *resource.StatusRequest) (*resource.StatusResult, error) {
	reqID, err := decodeLROStatus(request.RequestID)
	if err != nil {
		return &resource.StatusResult{ProgressResult: &resource.ProgressResult{
			OperationStatus: resource.OperationStatusFailure,
			RequestID:       request.RequestID,
			ErrorCode:       resource.OperationErrorCodeGeneralServiceException,
		}}, err
	}

	switch reqID.OperationType {
	case lroOpCreate, lroOpUpdate:
		operation := resource.OperationCreate
		if reqID.OperationType == lroOpUpdate {
			operation = resource.OperationUpdate
		}
		return statusLRO(ctx, request, &reqID, operation,
			func(token string) (*runtime.Poller[armcdn.AFDEndpointsClientCreateResponse], error) {
				return resumePoller[armcdn.AFDEndpointsClientCreateResponse](e.pipeline, token)
			},
			func(_ context.Context, result armcdn.AFDEndpointsClientCreateResponse, _ resource.Operation) (string, json.RawMessage, error) {
				rgName, profileName, endpointName, err := cdnAFDEndpointIDParts(*result.ID)
				if err != nil {
					return "", nil, err
				}
				propsJSON, err := serializeCdnAFDEndpointProperties(result.AFDEndpoint, rgName, profileName, endpointName)
				if err != nil {
					return "", nil, fmt.Errorf("failed to serialize AFDEndpoint properties: %w", err)
				}
				return *result.ID, propsJSON, nil
			})
	case lroOpDelete:
		return statusDeleteLRO(ctx, request, &reqID,
			func(token string) (*runtime.Poller[armcdn.AFDEndpointsClientDeleteResponse], error) {
				return resumePoller[armcdn.AFDEndpointsClientDeleteResponse](e.pipeline, token)
			}, nil)
	default:
		return &resource.StatusResult{ProgressResult: &resource.ProgressResult{
			OperationStatus: resource.OperationStatusFailure,
			RequestID:       request.RequestID,
			ErrorCode:       resource.OperationErrorCodeGeneralServiceException,
		}}, fmt.Errorf("unknown operation type: %s", reqID.OperationType)
	}
}

func (e *CdnAFDEndpoint) List(ctx context.Context, request *resource.ListRequest) (*resource.ListResult, error) {
	rgName := request.AdditionalProperties["resourceGroupName"]
	profileName := request.AdditionalProperties["profileName"]
	if rgName == "" || profileName == "" {
		return &resource.ListResult{}, nil
	}
	var nativeIDs []string
	pager := e.api.NewListByProfilePager(rgName, profileName, nil)
	for pager.More() {
		page, err := pager.NextPage(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to list afd endpoints: %w", err)
		}
		for _, x := range page.Value {
			if x != nil && x.ID != nil {
				nativeIDs = append(nativeIDs, *x.ID)
			}
		}
	}
	return &resource.ListResult{NativeIDs: nativeIDs}, nil
}
