// © 2025 Platform Engineering Labs Inc.
//
// SPDX-License-Identifier: FSL-1.1-ALv2

// REPRODUCTION ONLY - NOT FOR MERGE.
//
// These tests demonstrate that a @FieldHint on a field of a plain nested PKL class
// is silently discarded during schema extraction, so `hasProviderDefault` (and every
// other hint) is a no-op below the top level.
//
// Run:
//
//	go test ./pkg/registry/ -run TestRepro -v
//
// No cloud credentials and no Azure resources are required.
//
// # What breaks
//
// pkg/plugin/descriptors/Extractor.pkl builds a resource's hint map from
// formae.fq.hints(clazz). That walks the resource class's own properties, plus -
// recursively - the properties of any nested class that extends formae.SubResource:
//
//	function isSubResourceClass(cls) = cls.superclass != null &&
//	    (cls.superclass.name == "SubResource" || isSubResourceClass(cls.superclass))
//
// Nested hints are gathered through filter(isSubResourceType), so a nested class that
// does NOT extend formae.SubResource is skipped entirely and its annotations never
// reach Schema.Hints. Nothing warns; the annotation simply has no effect.
//
// # Why it matters
//
// The conformance runner decides whether a service-populated property is acceptable
// by looking the field path up in Schema.Hints
// (plugin-conformance-tests/runner.go: extractProviderDefaultPaths -> isProviderDefault).
// That lookup already understands dotted and array-indexed paths, so the comparison
// side is fine - the paths are simply never extracted. A field the provider always
// populates therefore reads as drift on every sync:
//
//	Property ipConfigurations[0].privateIpAllocationMethod is not expected
//	and not a provider default (after create / extract / sync / update)
//
// That is a real failure observed on AZURE::Network::BastionHost in CI
// (PR #127, run 33193494700, all four comparison phases). The host provisioned
// correctly; only the drift check failed.
//
// # Blast radius in this plugin
//
// Essentially every nested class in schema/pkl is a plain class rather than a
// formae.SubResource, so every hint on their fields is inert. TestReproBlastRadius
// prints the current counts rather than hardcoding them, so the numbers cannot rot.
//
// # Current workaround
//
// Contributors either declare the value explicitly in the conformance fixture, or drop
// it on the read path. Six resources carry hand-written comments about this; grep for
// "not honoured" / "not honored" under pkg/resources.
package registry

import (
	"context"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"testing"

	"github.com/platform-engineering-labs/formae/pkg/plugin"
	"github.com/platform-engineering-labs/formae/pkg/plugin/descriptors"
)

// formaeSchemaPackage must match the dependency in schema/pkl/PklProject.
const formaeSchemaPackage = "package://hub.platform.engineering/plugins/pkl/schema/pkl/formae/formae@0.89.0"

func extractAzureDescriptors(t *testing.T) []plugin.ResourceTypeDescriptor {
	t.Helper()
	project, err := filepath.Abs(filepath.Join("..", "..", "schema", "pkl", "PklProject"))
	if err != nil {
		t.Fatalf("resolve schema project path: %v", err)
	}
	// schema/pkl/VERSION is generated by `make build` and gitignored.
	if _, err := os.Stat(filepath.Join(filepath.Dir(project), "VERSION")); err != nil {
		t.Skipf("schema/pkl/VERSION missing - run `make build` first (%v)", err)
	}
	ds, err := descriptors.ExtractSchema(context.Background(), []descriptors.Dependency{
		{Name: "formae", Value: formaeSchemaPackage},
		{Name: "azure", Value: project},
	})
	if err != nil {
		t.Fatalf("ExtractSchema: %v", err)
	}
	return ds
}

func hintsFor(t *testing.T, ds []plugin.ResourceTypeDescriptor, resourceType string) map[string]any {
	t.Helper()
	for _, d := range ds {
		if d.Type == resourceType {
			out := make(map[string]any, len(d.Schema.Hints))
			for k, v := range d.Schema.Hints {
				out[k] = v
			}
			return out
		}
	}
	t.Fatalf("descriptor %q not found among %d extracted", resourceType, len(ds))
	return nil
}

// TestReproTopLevelHintSurvives is the control. A hasProviderDefault on a top-level
// field is extracted correctly, which is why the bug is easy to miss.
func TestReproTopLevelHintSurvives(t *testing.T) {
	hints := hintsFor(t, extractAzureDescriptors(t), "AZURE::Network::LoadBalancer")

	// schema/pkl/network/loadbalancer.pkl annotates `sku` at the top level.
	for _, field := range []string{"sku"} {
		if _, ok := hints[field]; !ok {
			t.Errorf("top-level field %q missing from Schema.Hints - "+
				"the control case is broken, so this test no longer isolates the nested bug", field)
		}
	}
}

// TestReproNestedHintIsDiscarded is the bug.
//
// schema/pkl/network/loadbalancer.pkl carries @azure.FieldHint { hasProviderDefault = true }
// on fields of two plain nested classes:
//
//	class Probe             -> intervalInSeconds, numberOfProbes
//	class LoadBalancingRule -> idleTimeoutInMinutes, disableOutboundSnat, loadDistribution
//
// None of those paths reach Schema.Hints, so the conformance runner cannot know the
// provider populates them.
func TestReproNestedHintIsDiscarded(t *testing.T) {
	hints := hintsFor(t, extractAzureDescriptors(t), "AZURE::Network::LoadBalancer")

	// The dotted form the runner's isProviderDefault() would look up. It strips array
	// indices before matching, so "probes[0].intervalInSeconds" also resolves here.
	wantNested := []string{
		"probes.intervalInSeconds",
		"probes.numberOfProbes",
		"loadBalancingRules.idleTimeoutInMinutes",
		"loadBalancingRules.disableOutboundSnat",
		"loadBalancingRules.loadDistribution",
	}

	var missing []string
	for _, path := range wantNested {
		if _, ok := hints[path]; !ok {
			missing = append(missing, path)
		}
	}

	if len(missing) > 0 {
		var got []string
		for k := range hints {
			got = append(got, k)
		}
		sort.Strings(got)
		t.Errorf("BUG: %d of %d nested hint paths were discarded during extraction.\n"+
			"  missing: %v\n"+
			"  Schema.Hints contains only top-level fields: %v\n\n"+
			"  Cause: pkg/plugin/descriptors/Extractor.pkl builds Hints from\n"+
			"  formae.fq.hints(clazz), which recurses only into nested classes that\n"+
			"  extend formae.SubResource (see isSubResourceClass in formae.pkl).\n"+
			"  A plain nested class is skipped and its annotations are dropped silently.",
			len(missing), len(wantNested), missing, got)
	}
}

// TestReproBlastRadius quantifies how many annotations the plugin has written that
// currently do nothing. It is informational and always passes - the failing signal is
// TestReproNestedHintIsDiscarded.
func TestReproBlastRadius(t *testing.T) {
	root := filepath.Join("..", "..", "schema", "pkl")
	classRe := regexp.MustCompile(`(?m)^\s*(?:open\s+)?class\s+(\w+)([^{]*)\{`)
	hintRe := regexp.MustCompile(`@azure\.FieldHint\s*\{[^}]*hasProviderDefault[^}]*\}\s*\n\s*(\w+)\s*:`)

	var droppedFields, droppedClasses, plainClasses, subResourceClasses int
	perFile := map[string][]string{}

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || filepath.Ext(path) != ".pkl" {
			return err
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		locs := classRe.FindAllStringSubmatchIndex(string(src), -1)
		for i, loc := range locs {
			name := string(src[loc[2]:loc[3]])
			ext := string(src[loc[4]:loc[5]])
			end := len(src)
			if i+1 < len(locs) {
				end = locs[i+1][0]
			}
			body := string(src[loc[1]:end])

			isResource := regexp.MustCompile(`formae\.Resource\b`).MatchString(ext)
			isSubResource := regexp.MustCompile(`SubResource\b`).MatchString(ext)
			if isResource {
				continue
			}
			if isSubResource {
				subResourceClasses++
				continue
			}
			plainClasses++

			fields := hintRe.FindAllStringSubmatch(body, -1)
			if len(fields) == 0 {
				continue
			}
			droppedClasses++
			rel, _ := filepath.Rel(root, path)
			for _, f := range fields {
				droppedFields++
				perFile[rel] = append(perFile[rel], name+"."+f[1])
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk schema: %v", err)
	}

	keys := make([]string, 0, len(perFile))
	for k := range perFile {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	t.Logf("nested classes extending formae.SubResource: %d", subResourceClasses)
	t.Logf("plain nested classes:                        %d", plainClasses)
	t.Logf("plain nested classes with dropped hints:     %d", droppedClasses)
	t.Logf("individual hint annotations with NO effect:  %d", droppedFields)
	for _, k := range keys {
		t.Logf("  %s: %v", k, perFile[k])
	}
}
